### ISSUE TITLE
Seite eines Spendenprojekts: Am Handy können keine Centbeträge eingegeben werden

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Frontend#103]

**Comment by CodingJosh42** [comment]
Am PC kann auch erst ab 9 Cent gespendet werden. @dermodmaster

**Comment by Alizame** [comment]
> Am PC kann auch erst ab 9 Cent gespendet werden. @dermodmaster

das kann ich nicht reproduzieren

**Comment by CodingJosh42** [comment]
> 
> 
> > Am PC kann auch erst ab 9 Cent gespendet werden. @dermodmaster
> 
> das kann ich nicht reproduzieren

Inwiefern? Du kannst auch bei Beträgen darunter spenden oder kannst du nicht bei 9 Cent spenden?

**Comment by Alizame** [comment]
> > > Am PC kann auch erst ab 9 Cent gespendet werden. @dermodmaster
> > 
> > 
> > das kann ich nicht reproduzieren
> 
> Inwiefern? Du kannst auch bei Beträgen darunter spenden oder auch nicht bei 9 Cent?

ich kann auch ohne probleme 0,01€ spenden. 

ist dein Fehler evtl dieser hier: #125

**Comment by CodingJosh42** [comment]
Ne hab ich eigentlich selber disabled

**Comment by CodingJosh42** [comment]
ne jetzt gehts wieder. Wtf ich hasse web Entwicklung. Weird shit
