### ISSUE TITLE
Portfolio reparieren

### ISSUE THREAD

**Issue by xGurke** [Software-Projekt-Thiel-2020/Frontend#108]
Das Portfolio kann nicht mehr dargestellt werden

Branch Portfolio_fix

**Comment by CodingJosh42** [comment]
Was genau wird bei dem Portfolio nicht angezeigt? Die Gutscheine und die Spenden?

**Comment by xGurke** [comment]
> Was genau wird bei dem Portfolio nicht angezeigt? Die Gutscheine und die Spenden?

Auf dem jetzigem Stand vom Master wird gar nichts angezeigt. Auf dem Branch Portfolio_fix habe ich das grobe schon mal behoben. Aber es liegen immer noch einige Konsolen Fehler vor.

**Comment by CodingJosh42** [comment]
> 
> 
> > Was genau wird bei dem Portfolio nicht angezeigt? Die Gutscheine und die Spenden?
> 
> Auf dem jetzigem Stand vom Master wird gar nichts angezeigt. Auf dem Branch Portfolio_fix habe ich das grobe schon mal behoben. Aber es liegen immer noch einige Konsolen Fehler vor.

Die Konsolenfehler habe ich behoben. Sind noch andere Fehler? Sonst würde ich eine Pull request erstellen (oder du, wie du willst).
