### ISSUE TITLE
/Projektanlegen Warnung in Konsole fixen: watcher

### ISSUE THREAD

**Issue by Sascha-Ruehrup** [Software-Projekt-Thiel-2020/Frontend#115]

**Comment by CodingJosh42** [comment]
Welcher Branch?

**Comment by Sascha-Ruehrup** [comment]
Den Watcher habe ich beim erstellen des v-data-table mit übernommen. Für mich ist im nachhinein nicht ersichtlich, wozu dieser nötig ist, da aus meiner Sicht die Funktionalität gleichgeblieben ist, nachdem der Watcher entfernt wurde. es wurde 'this.close' aufgerufen, nachdem sich ein boolean in data geändert hat, allerdings wird this.close schon dort aufgerufen, wo das Dialogfenster geschlossen werden soll. es gab ebenfalls Probleme mit ESLint, da eine variable keine Verwendung hatte.
