### ISSUE TITLE
Projektanlegen: Invalid Date, wenn beim Bearbeiten das Datum nicht eingegeben wird.

### ISSUE THREAD

**Issue by Sascha-Ruehrup** [Software-Projekt-Thiel-2020/Frontend#131]
Wenn man einen Meilenstein bearbeitet, wird die Zeit until nicht in den Datepicker geladen. Der Datepicker interpretiert das Datum aus 'editedItem' falsch, wodurch 'Error in render: "RangeError: date value is not finite in DateTimeFormat.format()" ' und bei der Tabelle in der Spalte Meilensteinende 'Invalid Date' erscheint.

**Comment by xGurke** [comment]
Ich glaube ich habe das Problem unter dem PR "Projekt Seiten merge #166" gelöst
