### ISSUE TITLE
/projektanlegen: Meilensteine fixen

### ISSUE THREAD

**Issue by xGurke** [Software-Projekt-Thiel-2020/Frontend#194]
Beim Anlegen eines Projektes werden die Meilensteine nicht richtig abgespeichert. 
Außerdem kann man den 'Neuer Meilenstein' Dialog nicht per 'Cancel'-Button schließen. wenn man einmal einen Meilenstein-Namen eingegeben hat und diesen wieder löscht.
Hinzu kommt, dass manchmal Komma Werte für until gesendet werden.

[Letze Änderung an der Datei](https://github.com/Software-Projekt-Thiel-2020/Frontend/commit/ccab45ef14934d87d1fd7ce35565907fa9da2133)

**Comment by Sascha-Ruehrup** [comment]
Den Teil mit kommawerten für until: Der until-Wert wird beim erstellen / 1000 geteilt und am ende nochmal, wenn der header erstellt wird. das /1000 im header entfernen?

Das mit dem Cancel-Button kann ich nicht ganz nachstellen. meinst du, nachdem man bearbeitet, dabei den namen entfernt und dann cancel drückt, dass dann in der Auflistung der Name fehlt? da, wo in editItem copy zugewiesen wird, muss copy auf editedItem gemapped(?) werden. statt ' = copy ' -> ' = { ...copy } ', dann sollte er die Werte richtig übernehmen. Hatte vorhin schon nen neuen Branch angelegt und 2 sachen geändert, aber da scheint wohl was schief gelaufen zu sein. #186

**Comment by Sascha-Ruehrup** [comment]
Hab nen Pullrequest für die until-Änderung erstellt. die andere sache war schon auf dem master gefixed.
