### ISSUE TITLE
Meilensteinvoting visuelle Rückmeldung

### ISSUE THREAD

**Issue by 0xalwayslucky** [Software-Projekt-Thiel-2020/Frontend#209]
/portfolio

- [x] medium: Visuelle Rückmeldung für Voting wird nicht immer geladen (Farben der Thumbs-up und Thumbs-down buttons)

**Comment by Alizame** [comment]
Könnte möglicherweise ein Backend Issue sein,
Falls das der Fall ist, fehlt hier ein Feedback, das es nicht geklappt hat!

**Comment by 0xalwayslucky** [comment]
evtl auch sinnvoll ein popup zu implementieren welches das voting bestätigt da man seine stimme nicht noch einmal ändern kann
