### ISSUE TITLE
Suche nach Spendenprojekte und Betrieben in der Nähe fehlerhaft

### ISSUE THREAD

**Issue by 0xalwayslucky** [Software-Projekt-Thiel-2020/Frontend#210]
bei /spenden und /gutscheine

- [x] medium: Radius funktion funktioniert nicht

- [x] medium: Nach wechseln des Ländercodes bleibt Suchen Button disabled

- [x] medium: Nachdem man Stadt/PLZ angegeben hat und man das Feld wieder leert um nach etwas neuen zu Suchen werden keine Projekte mehr angezeigt, die nicht zu dem Ort gehören

**Comment by CodingJosh42** [comment]
Radius Funktion funktioniert nur bei Spendenprojekten nicht, weil nach der Position der Institutionen gefiltert wird und nicht nach der Position der Spendenprojekte

**Comment by CodingJosh42** [comment]
Ich glaube das ist dann eher ein Problem im Backend @Alizame @maxkleinke

**Comment by Alizame** [comment]
- Also bei mir funktioniert das mit dem Radius, sowohl über die PLZ/Stadt, als auch über das Browser-Positions-Dings?
- Missversständnis: Der Ländercode bezieht sich nicht direkt auf die Ergebnisse die man erhält, sondern auf die PLZ/Stadt die man angibt
- Der letzte Punkt ist korrekt, wenn ich das PLZ/Stadt feld lösche und dann etwas beim namen eingebe erhalte ich keine Ergebnisse da lat&long immernoch mitgesendet werden und daher keine gefunden werden. Erst nach drücken des Zurücksetzten Btns wird auch die Position nicht mehr mitgesendet

> Radius Funktion funktioniert nur bei Spendenprojekten nicht, weil nach der Position der Institutionen gefiltert wird und nicht nach der Position der Spendenprojekte

stimmte, ist jetzt gefixt
