### ISSUE TITLE
Spendenprojekt erstellen

### ISSUE THREAD

**Issue by 0xalwayslucky** [Software-Projekt-Thiel-2020/Frontend#213]
/projektanlegen
- [x] low: Fehlende visuelle input validation bei Latitude und Longitude (Eingabe von nicht numerischen Zeichen wird als valide angezeigt)

- [x] low: Keine Rückmeldung falls Projekt mit gleichem namen bereits besteht (400 bad request)

**Comment by CodingJosh42** [comment]
Also ich kann mehrere Projekte mit dem gleichen Namen erstellen. Um zu verhindern das ein Name doppelt ist müsste man alle Projekte laden und die Namen vergleichen. Glaube das ist eher ein Backend Problem. @maxkleinke @Alizame
