### ISSUE TITLE
Große GOAL Zahlen richtig behandeln

### ISSUE THREAD

**Issue by xGurke** [Software-Projekt-Thiel-2020/Frontend#217]
Im gesamten Projekt werden große Zahlen, welche WEI darstellen nur als Number gehandhabt. Number kann aber in JS "nur" (2^53)-1, für einen sicheren Umgang, groß sein. Werte dadrüber werden nicht richtig gehandhabt. Außerdem hat sich das Senden im Backend auch entsprechend angepasst und sendet nun Strings anstatt von Integern.

**Comment by Alizame** [comment]
Dadurch, dass das Backend nun Strings sendet, entstehen überall dort wo man Wei-Zahlen eingeben kann Fehler, da nun strings mit numbern verglichen werden

- [ ] ProjektAnlegen
- [ ] ProjektEditieren
- [ ] InstitutionVoucher
