### ISSUE TITLE
ProjektAnlegen: Milestone Edit Bug

### ISSUE THREAD

**Issue by xGurke** [Software-Projekt-Thiel-2020/Frontend#219]
Das Editieren der angelegten Meilensteine hat noch einen Bug:
Wenn man mehrere Meilensteine (M1 und M2) hat und den ersten bearbeiten will, dann aber auf 'cancel' drück, werden diese flasch abgespeichert und man erhält in project.milestones zwei mal den Milestone M1.
Der Fehler wird auch so abgesendet.

Beobachtung: Wenn man n Meilensteine hat und den x-ten bearbeitet und cancelt, dann ist Meilenstein x+1 falsch unter projejt.milestones abgespeichert.

**Comment by Sascha-Ruehrup** [comment]
Das Problem tritt auch auf, wenn ganz normal eine Änderung gespeichert wird. ich würde den Fehler somit erstmal auf die save() methode eingrenzen. ich schaus mir mal an.

**Comment by Sascha-Ruehrup** [comment]
Ich glaube, jetzt sollte das Problem behoben sein nicht mehr auftreten. Ich habe es jetzt so umstrukturiert, dass jeweils auf dem gleichen Index in den beiden Meilenstein-Arrays gearbeitet wird. Ich erstelle mal ne pull-request.
