### ISSUE TITLE
Input validation Meilenstein anlegen/editieren

### ISSUE THREAD

**Issue by 0xalwayslucky** [Software-Projekt-Thiel-2020/Frontend#235]
Meilensteinname und Spendenziel können leer sein, nur Datum ist erfordert um einen hinzuzufügen

to reproduce:
Projekt editieren/anlegen
Meilenstein hinzufügen
Datum angeben
Save drücken

**Comment by xGurke** [comment]
Der letzte Commit wurde nicht mit auf spenderderschlender gepusht. In dem wurde das Problem beim Editieren gefixt. Beim Anlegen trat der Bug bei mir nicht auf.
