### ISSUE TITLE
Seite erstellen um den Benutzer zu regestrieren

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Frontend#37]

**Comment by CodingJosh42** [comment]
@dermodmaster registrieren wir uns nicht über Blockstack?

**Comment by Alizame** [comment]
Ja, da fehlen dann aber noch Daten die in die DB gehören (siehe POST /users )

**Comment by CodingJosh42** [comment]
@Alizame  Also man registriert sich auf Blockstack und dann zusätzlich auf unserer Seite?

**Comment by Alizame** [comment]
Würde es eher ein "vervollständigen der Nutzer-Daten" nennen

**Comment by CodingJosh42** [comment]
@Alizame aber wie wollen wir dann überprüfen ob sich ein User bereits registriert hat?

**Comment by Alizame** [comment]
Wenn bei einem GET /users?id={seine blockstack id} nur eine Leere Liste zurückgegeben wird, dann ist er noch nicht registriert.

**Comment by CodingJosh42** [comment]
Das heißt man kann sich nur registrieren wenn man sich vorher bei Blockstack registriert hat richtig?

**Comment by Alizame** [comment]
- Man kommt zum ersten mal auf unsere Seite
- klickt auf anmelden mit blockstack
- ...
- wird zurückgeleitet auf unsere Seite
- eine Meldung geht auf das man bitte sein Profil vervollständigen soll
- man tut dies und drückt auf übernehmen (oder so)
- ??? 
- Profit
