### ISSUE TITLE
Bilder Upload für Institutionen

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Frontend#83]
Wir brauchen eine Seite wo der Inhaber einer Institution die Beschreibung und ein Bild anpassen kann, allerdings beschränkt sich dieses Issue erstmal nur auf den Bilderupload, da das mit der Beschreibung auf Waiting steht #84 

**Wartet auf Assoziation zwischen User und Institution**

**Comment by CodingJosh42** [comment]
@dermodmaster Wie komme ich denn an den Inhaber einer Seite? Finde im API-Viewer keine geeignete Route dazu

**Comment by CodingJosh42** [comment]
Inhaber einer Institution wird nicht abgespeichert, deshalb pausiert.
