### ISSUE TITLE
Projekt überprüfen auf Währungseinheit Wei

### ISSUE THREAD

**Issue by dermodmaster** [Software-Projekt-Thiel-2020/Frontend#89]
Wir haben mit dem Backend vereinbart, dass das Backend Ethereum Beträge nur in Wei zurückgibt. Diese müssten bei der Anzeige ggf umgerechnet werden. Hier muss die Logik überprüft werden ob irgendwo noch mit Ethereum und nicht mit Wei gerechnet wird.

**Comment by Alizame** [comment]
Bei der Projekt-Spendenseite (bspw: https://spenderschlender.3ef.de/#/project/1) stimmt die Umrechnung bei den Meilensteinen nicht, die scheint um den Faktor 10 zu klein zu sein, und das % ist dann auch falsch
